// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf28B2WHZ_3XrLRC2_xf6Q6MhkCvXOLQA',
    appId: '1:393783388275:web:32363d97648fcf11772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    authDomain: 'chat-68e71.firebaseapp.com',
    storageBucket: 'chat-68e71.firebasestorage.app',
    measurementId: 'G-BKJEGW68C7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbuTteQhicJMc6cGSYdnwcGzvrxccYhsI',
    appId: '1:393783388275:android:b06f14f89ff35fc2772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    storageBucket: 'chat-68e71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9idUkwMjkoHR7Mgx1Xftc7cAnHx5i0Sc',
    appId: '1:393783388275:ios:8d8144245fe929d7772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    storageBucket: 'chat-68e71.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9idUkwMjkoHR7Mgx1Xftc7cAnHx5i0Sc',
    appId: '1:393783388275:ios:8d8144245fe929d7772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    storageBucket: 'chat-68e71.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDf28B2WHZ_3XrLRC2_xf6Q6MhkCvXOLQA',
    appId: '1:393783388275:web:4c796293c3ece54d772206',
    messagingSenderId: '393783388275',
    projectId: 'chat-68e71',
    authDomain: 'chat-68e71.firebaseapp.com',
    storageBucket: 'chat-68e71.firebasestorage.app',
    measurementId: 'G-ZSH44R6BYQ',
  );
}
